name       : smplayer
version    : 18.1.0
release    : 27
source     :
    - https://jaist.dl.sourceforge.net/project/smplayer/SMPlayer/18.1.0/smplayer-18.1.0.tar.bz2 : 9d7d908c5160510e8802fbf852598324fd80ca9a8a571b8e65d66b39ec0b19bd
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
rundeps    :
    - mpv
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
