name       : smplayer
version    : 16.11.0
release    : 11
source     :
    - http://internode.dl.sourceforge.net/project/smplayer/SMPlayer/16.11.0/smplayer-16.11.0.tar.bz2 : e53a5d8b4d66fb0b7eb73053ef0bfdd2d942b79a16f8cc8d3d0b0771c7c80b5a
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(Qt5Core)
rundeps    :
    - mpv
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
