name       : smplayer
version    : 16.1.0
release    : 3
source     :
    - http://ncu.dl.sourceforge.net/project/smplayer/SMPlayer/16.1.0/smplayer-16.1.0.tar.bz2 : d25c9b62d36c5ee63fb360e9a45566601d49d707e1364294a54967b956bdd8c9
license    :
    - GPL-2.0
    - BSD-3-Clause
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
    One of the most interesting features of SMPlayer: it remembers the settings of all files you play. So you start to watch a movie but you have to leave... don't worry, when you open that movie again it will be resumed at the same point you left it, and with the same settings: audio track, subtitles, volume...
    SMPlayer is a graphical user interface (GUI) for the award-winning MPlayer, which is capable of playing almost all known video and audio formats. But apart from providing access for the most common and useful options of MPlayer, SMPlayer adds other interesting features like the possibility to play Youtube videos or download subtitles.
rundeps    :
    - mpv
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(glesv2)
build      : |
    %make
install    : |
    %make_install
    #Fix /usr/local crap
    mv %installroot%/usr/local/share %installroot%/usr/
    mv %installroot%/usr/share/doc/packages/smplayer %installroot%/usr/share/doc/
    mv %installroot%/usr/local/bin %installroot%/usr
    
