name       : smplayer
version    : 16.8.0
release    : 8
source     :
    - http://pilotfiber.dl.sourceforge.net/project/smplayer/SMPlayer/16.8.0/smplayer-16.8.0.tar.bz2 : 3ced2085808798bd2cdb1ca623686dbde3ac6b7acccee9de4786a2d5f96d9c81
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(glesv2)
rundeps    :
    - mpv
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
