name       : smplayer
version    : 19.5.0
release    : 33
source     :
    - https://datapacket.dl.sourceforge.net/project/smplayer/SMPlayer/19.5.0/smplayer-19.5.0.tar.bz2 : b5cb2b37fc9a225bb7287bf26a0a499f7b46bff688161b8e5eae0d96d74daaf5
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
rundeps    :
    - mpv
build      : |
    %make PREFIX=%PREFIX% QMAKE_OPTS=DEFINES+=NO_DEBUG_ON_CONSOLE
install    : |
    %make_install PREFIX=%PREFIX%
