name       : smplayer
version    : 16.9.0
release    : 9
source     :
    - http://jaist.dl.sourceforge.net/project/smplayer/SMPlayer/16.9.0/smplayer-16.9.0.tar.bz2 : 692e49fbfbcedaecf9e41f40e3f49905ec4d967e0b99b2c8c5fec1b6810ccdbe
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(glesv2)
rundeps    :
    - mpv
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
