name       : smplayer
version    : 17.9.0
release    : 22
source     :
    - https://nchc.dl.sourceforge.net/project/smplayer/SMPlayer/17.9.0/smplayer-17.9.0.tar.bz2 : 2af0090b9607acace1b275f9349a50645f784f72cc0bd6454b02515e99292869
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
rundeps    :
    - mpv
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
