name       : smplayer
version    : 17.4.2
release    : 18
source     :
    - https://jaist.dl.sourceforge.net/project/smplayer/SMPlayer/17.4.2/smplayer-17.4.2.tar.bz2 : 05577880df3620ab238a9a28055816c8e97d294ad4b2b39eb7de9be281bc85d1
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : multimedia.video
summary    : Free Media Player with built-in codecs. Play all audio and video formats.
description: |
    SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Script)
rundeps    :
    - mpv
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
